backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: src/assets/uploads
public_folder: /uploads
collections:
  - name: blog
    label: Entry
    folder: src/pages/entries
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - label: Module
        name: module
        widget: hidden
        default: Static.Entry
      - label: Title
        name: title
        widget: string
      - label: Category
        name: category
        widget: select
        multiple: true
        min: 1
        options:
          - comment
          - us
          - jp
          - yoyo
          - code
      - label: Publish Date
        name: date
        widget: date
        format: YYYY-MM-DD
      - label: Body
        name: body
        widget: markdown
editor:
  preview: false
sortableFields:
  - date
  - title
  - category
